-- SOLUCIÓN
-- LISTAR TODOS LOS PRODUCTOS ORDENADOS DE MENOR A MAYOR PRECIO
SELECT * FROM producto ORDER BY precio;
-- LISTAR TODAS LAS FÁBRICAS ORDENADAS POR NOMBRE ASCENDENTE
SELECT * FROM fabrica ORDER BY nombre asc;
-- OBTENER NOMBRE Y PRECIO DE PRODUCTOS QUE VALOR MAYOR A $300
SELECT nombre, precio FROM producto where precio > 300;
-- OBTENER NOMBRE Y PRECIO DEL PRODUCTO DE MENOR PRECIO
SELECT nombre, precio FROM producto where precio = (SELECT MIN(precio) FROM producto);