-- SOLUCIÓN DE EJECRCICIO

-- TODOS LOS SOCIOS
SELECT * FROM socio;
-- TODOS LOS DEPORTES
SELECT * FROM deporte;
-- TODOS LOS SOCIOS QUE PRACTIQUEN TENIS
SELECT * FROM socio WHERE fk_codigo IN (SELECT codigo FROM deporte WHERE nombre = 'Tenis');
-- CONTEO DE TODOS LOS SOCIOS QUE PRACTIQUEN FUTBOL
SELECT COUNT(*) FROM socio WHERE fk_codigo IN (SELECT codigo FROM deporte WHERE nombre = 'Fútbol');